export const BLUETOOTHON = 'BLUETOOTHON';
export const BLUETOOTHOFF = 'BLUETOOTHOFF';
export const RESET = 'RESET';
export const CHANGECURRENTDEVICE = 'CHANGECURRENTDEVICE';
export const ADDDEVICE = 'ADDDEVICE';
export const UPDATEDEVICE = 'UPDATEDEVICE';
export const SETMESSAGE = 'SETMESSAGE';
